#include "draw.h"
#include "gba.h"
#include "images/arrows.h"

// TA-TODO: Include any header files for images generated by nin10kit.
// Example for the provided garbage image:
// #include "images/garbage.h"

// TA-TODO: Add any draw/undraw functions for sub-elements of your app here.
// For example, for a snake game, you could have a drawSnake function
// or a drawFood function
//
// e.g.:
// static void drawSnake(Snake* snake);
// static void drawFood(Food* food);

// This function will be used to draw everything about the app
// including the background and whatnot.
void fullDrawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    for (int i = 0; i < 10; i++) {
        drawImageDMA(0, state->lefts[i], 32, 32, left);
        drawImageDMA(32, state->downs[i], 32, 32, down);
        drawImageDMA(64, state->ups[i], 32, 32, up);
        drawImageDMA(96, state->rights[i], 32, 32, right);
        drawImageDMA(128, state->As[i], 32, 32, A);
        drawImageDMA(160, state->Bs[i], 32, 32, B);
    }
}

// This function will be used to undraw (i.e. erase) things that might
// move in a frame. E.g. in a Snake game, erase the Snake, the food & the score.
void undrawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    for (int i = 0; i < 10; i++) {
        drawRectDMA(0, state->lefts[i], 32, 32, BLACK);
        drawRectDMA(32, state->downs[i], 32, 32, BLACK);
        drawRectDMA(64, state->ups[i], 32, 32, BLACK);
        drawRectDMA(96, state->rights[i], 32, 32, BLACK);
        drawRectDMA(128, state->As[i], 32, 32, BLACK);
        drawRectDMA(160, state->Bs[i], 32, 32, BLACK);
    }
}

// This function will be used to draw things that might have moved in a frame.
// For example, in a Snake game, draw the snake, the food, the score.
void drawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    fullDrawAppState(state);
}
